#!/bin/sh

# PROVIDE: Betcoin
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# Betcoin_enable (bool): Set to NO by default. Set this variable to YES if you want to enable Betcoin service.
# Betcoin_config (path): Set to /usr/local/etc/Betcoin.conf by default.
# Betcoin_user:  The user account Betcoin daemon runs as. It uses 'root' user by default.
# Betcoin_group: The group account Betcoin daemon runs as. It uses 'wheel' group by default.
# Betcoin_datadir (str): Default to "/var/db/Betcoin". Base data directory.

. /etc/rc.subr

name=Betcoin
rcvar=Betcoin_enable

: ${Betcoin_enable:=NO}
: ${Betcoin_config=/usr/local/etc/Betcoin.conf}
: ${Betcoin_datadir=/var/db/Betcoin}
: ${Betcoin_user="root"}
: ${Betcoin_group="wheel"}

required_files=${Betcoin_config}
command=/usr/local/bin/Betcoind
Betcoin_chdir=${Betcoin_datadir}
pidfile="${Betcoin_datadir}/Betcoind.pid"
stop_cmd=Betcoin_stop
command_args="-conf=${Betcoin_config} -datadir=${Betcoin_datadir} -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

Betcoin_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${Betcoin_datadir}
	[ $? -eq 0 ] && chown -R ${Betcoin_user}:${Betcoin_group} ${Betcoin_datadir}
}

Betcoin_prestart()
{
	if [ ! -d "${Betcoin_datadir}/." ]; then
		Betcoin_create_datadir || return 1
	fi
}

Betcoin_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

Betcoin_stop()
{
    Betcoin_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${Betcoin_config} -datadir=${Betcoin_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
